export const API_CONSTANTS = {
  GET_WEATHER_DETAILS_LOAD: "GET_WEATHER_DETAILS_LOAD",
  GET_WEATHER_DETAILS_SUCCESS: "GET_WEATHER_DETAILS_SUCCESS",
  GET_WEATHER_CONDITIONS_IN_CURRENT_CITY_LOAD:
    "GET_WEATHER_CONDITIONS_IN_CURRENT_CITY_LOAD",
  GET_WEATHER_CONDITIONS_IN_CURRENT_CITY_SUCCESS:
    "GET_WEATHER_CONDITIONS_IN_CURRENT_CITY_LOAD_SUCCESS",
  GET_WEATHER_CONDITIONS_IN_CURRENT_CITY_FAILUER:
    "GET_WEATHER_CONDITIONS_IN_CURRENT_CITY_FAILUER",
};
